In [1]:
import pandas as pd
import numpy as np

In [2]:
# Data Load
df = pd.read_excel(r"D:\End to End Project\Performance_Tracker\Employee_Performance_Tracker.xlsx")

In [3]:
df.head()

,EmployeeID,EmployeeName,Department,Manager,Month,Target,Achievement,AttendancePercent,TrainingHours,PerformanceRating,AchievementPercent,PerformanceCategory
0,EMP1000,Employee_0,Customer Service,Rahul Verma,2024-08-01,188,132,89.70,18.8,3,70.21,Meets Expectation
1,EMP1001,Employee_1,HR,Priya Sharma,2024-03-01,192,57,91.26,2.5,5,29.69,Below Expectation
2,EMP1002,Employee_2,Operations,Ravi Patel,2024-10-01,184,70,70.25,17.5,5,38.04,Below Expectation
3,EMP1003,Employee_3,Customer Service,Amit Kumar,2024-03-01,77,128,76.53,19.4,3,166.23,Outstanding
4,EMP1004,Employee_4,Finance,Suresh Iyer,2024-08-01,100,76,89.85,3.5,3,76.00,Meets Expectation

In [4]:
df.shape

(1000, 12)

In [6]:
df.describe()

,Month,Target,Achievement,AttendancePercent,TrainingHours,PerformanceRating,AchievementPercent
count,1000,1000.000000,1000.000000,1000.000000,1000.000000,1000.00000,1000.000000
mean,2024-06-13 20:54:14.400000,126.526000,125.284000,84.821280,9.900300,3.00000,114.287000
min,2024-01-01 00:00:00,50.000000,30.000000,70.000000,0.000000,1.00000,16.130000
25%,2024-03-01 00:00:00,88.000000,82.000000,77.375000,4.800000,2.00000,65.060000
50%,2024-06-01 00:00:00,127.000000,125.000000,84.780000,9.700000,3.00000,98.480000
75%,2024-09-01 00:00:00,166.000000,170.000000,92.147500,15.000000,4.00000,145.112500
max,2024-12-01 00:00:00,199.000000,219.000000,99.990000,19.900000,5.00000,425.490000
std,NaN,44.265797,53.669468,8.585494,5.774866,1.09325,70.424069

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 12 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   EmployeeID           1000 non-null   object
 1   EmployeeName         1000 non-null   object
 2   Department           1000 non-null   object
 3   Manager              1000 non-null   object
 4   Month                1000 non-null   datetime64[ns]
 5   Target               1000 non-null   int64
 6   Achievement          1000 non-null   int64
 7   AttendancePercent    1000 non-null   float64
 8   TrainingHours        1000 non-null   float64
 9   PerformanceRating    1000 non-null   int64
 10  AchievementPercent   1000 non-null   float64
 11  PerformanceCategory  879 non-null    object
dtypes: datetime64[ns](1), float64(3), int64(3), object(5)
memory usage: 93.9+ KB

In [8]:
df.isnull().sum()

EmployeeID               0
EmployeeName             0
Department               0
Manager                  0
Month                    0
Target                   0
Achievement              0
AttendancePercent        0
TrainingHours            0
PerformanceRating        0
AchievementPercent       0
PerformanceCategory    121
dtype: int64

In [9]:
# Department
df['Department'].value_counts()

Department
HR                  156
Sales               156
Operations          148
Customer Service    138
Marketing           137
IT                  135
Finance             130
Name: count, dtype: int64

In [10]:
#Manager
df['Manager'].value_counts()

Manager
Amit Kumar      151
Ravi Patel      149
Suresh Iyer     147
Priya Sharma    145
Anjali Mehta    145
Rahul Verma     143
Neha Singh      120
Name: count, dtype: int64

In [11]:
#PerformanceCategory
df['PerformanceCategory'].value_counts()

PerformanceCategory
Outstanding            372
Below Expectation      294
Meets Expectation      142
Exceeds Expectation     71
Name: count, dtype: int64

In [12]:
df['PerformanceCategory'].isnull().sum()

np.int64(121)

In [16]:
# fill the null value
df['PerformanceCategory'] = df['PerformanceCategory'].fillna('Not Rated')

In [17]:
df['PerformanceCategory'].isnull().sum()

np.int64(0)

In [18]:
df.isnull().sum()

EmployeeID             0
EmployeeName           0
Department             0
Manager                0
Month                  0
Target                 0
Achievement            0
AttendancePercent      0
TrainingHours          0
PerformanceRating      0
AchievementPercent     0
PerformanceCategory    0
dtype: int64

In [19]:
# Month
df['Month'] = pd.to_datetime(df['Month'], errors='coerce')

In [20]:
df.head()

,EmployeeID,EmployeeName,Department,Manager,Month,Target,Achievement,AttendancePercent,TrainingHours,PerformanceRating,AchievementPercent,PerformanceCategory
0,EMP1000,Employee_0,Customer Service,Rahul Verma,2024-08-01,188,132,89.70,18.8,3,70.21,Meets Expectation
1,EMP1001,Employee_1,HR,Priya Sharma,2024-03-01,192,57,91.26,2.5,5,29.69,Below Expectation
2,EMP1002,Employee_2,Operations,Ravi Patel,2024-10-01,184,70,70.25,17.5,5,38.04,Below Expectation
3,EMP1003,Employee_3,Customer Service,Amit Kumar,2024-03-01,77,128,76.53,19.4,3,166.23,Outstanding
4,EMP1004,Employee_4,Finance,Suresh Iyer,2024-08-01,100,76,89.85,3.5,3,76.00,Meets Expectation

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 12 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   EmployeeID           1000 non-null   object
 1   EmployeeName         1000 non-null   object
 2   Department           1000 non-null   object
 3   Manager              1000 non-null   object
 4   Month                1000 non-null   datetime64[ns]
 5   Target               1000 non-null   int64
 6   Achievement          1000 non-null   int64
 7   AttendancePercent    1000 non-null   float64
 8   TrainingHours        1000 non-null   float64
 9   PerformanceRating    1000 non-null   int64
 10  AchievementPercent   1000 non-null   float64
 11  PerformanceCategory  1000 non-null   object
dtypes: datetime64[ns](1), float64(3), int64(3), object(5)
memory usage: 93.9+ KB

In [22]:
# Save the file 
df.to_excel('Performance_Dataclean.xlsx', index=False)